version: '3.3'

services:

  frontend:
    container_name: frontend
    build:
      context: ./web2
    ports:
      - "3000:3000"
    env_file:
      - "./web2/.env"
    depends_on:
     - db
     - server1
     - server2

  db:
    container_name: quickdb
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "long_password_here"
      MYSQL_DATABASE: "quickdb"

  server1:
    container_name: server1
    build:
      context: ./server
    links:
      - "db:database"
    env_file:
      - "./server/.env"
    depends_on:
     - db
    
  server2:
    container_name: server2
    build:
      context: ./server
    links:
      - "db:database"
    env_file:
      - "./server/.env"
    depends_on:
      - db

  load_balancer:
    restart: always
    build:
      context: ./nginx
    links:
      - "server1:server_one"
      - "server2:server_two"
      - "frontend:frontend_one"
      - "adminer:admin_one"
    ports:
      - "80:80"
      - "443:443"

    depends_on:
      - server1
      - server2
      - db
      - frontend


  adminer:
    image: adminer
    restart: always
    links:
      - "db:database"
    depends_on:
      - db
