version: '3.3'

services:
  db:
    container_name: quickdb
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "long_password_here"
      MYSQL_DATABASE: "quickdb"

  server1:
    container_name: server1
    build:
      context: ./server
    ports:
      - "4001:4000"
    links:
      - "db:database"
    env_file:
      - "./server/.env"
    depends_on:
     - db
    
  server2:
    container_name: server2
    build:
      context: ./server
    ports:
      - "4002:4000"
    links:
      - "db:database"
    env_file:
      - "./server/.env"
    depends_on:
      - db

  load_balancer:
    restart: always
    build:
      context: ./nginx
    network_mode: "host"
    depends_on:
      - server1
      - server2
      - db


  adminer:
    image: adminer
    restart: always
    ports:
      - 10000:8080
    links:
      - "db:database"
    depends_on:
      - db